pipeline:

  deploy:
    image: docker
    secrets: [ LOGZIO_TOKEN ]
    commands:
      - docker deploy --compose-file docker-compose.yml logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock