version: "3"
services:
  logzio:
    command: -t ${LOGZIO_TOKEN} -z us -a env=prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    image: logzio/logzio-docker
